@host=https://localhost:7224

POST  {{host}}/auth/register HTTP/1.1
content-type: application/json 

{
    "firstName": "Arnaud",
    "lastName": "Muller",
    "email": "arnaud.muller@gmail.com",
    "password": "Arnaud1232!"
}